/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.UIManager;
import controladores.controladorSidebar;

/**
 *
 * @author Adrian
 */
public class menuSidebar extends javax.swing.JFrame {

    /**
     * Creates new form menuSidebar
     */
    public menuSidebar() {
        initComponents();
        setLocationRelativeTo(this);
        
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "src/imagenes/preview.jpg");
        controladorSidebar ConSidebar = new controladorSidebar(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTN_AGENDAR = new javax.swing.JButton();
        BTN_DASHBOARD = new javax.swing.JButton();
        BTN_ESPECIALIDAD = new javax.swing.JButton();
        BTN_CITAS = new javax.swing.JButton();
        BTN_DOCTORES = new javax.swing.JButton();
        ventanaInicial = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(157, 195, 231));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/preview.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 80));

        BTN_AGENDAR.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTN_AGENDAR.setText("Agendar");
        BTN_AGENDAR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTN_AGENDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AGENDARActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_AGENDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 130, 40));

        BTN_DASHBOARD.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTN_DASHBOARD.setText("Dashboard");
        BTN_DASHBOARD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BTN_DASHBOARD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DASHBOARDActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_DASHBOARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, 40));

        BTN_ESPECIALIDAD.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTN_ESPECIALIDAD.setText("Especialidades");
        BTN_ESPECIALIDAD.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        BTN_ESPECIALIDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ESPECIALIDADActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_ESPECIALIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 40));

        BTN_CITAS.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTN_CITAS.setText("Citas");
        BTN_CITAS.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        BTN_CITAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CITASActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_CITAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 40));

        BTN_DOCTORES.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BTN_DOCTORES.setText("Doctores");
        BTN_DOCTORES.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        BTN_DOCTORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_DOCTORESActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_DOCTORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 40));

        ventanaInicial.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ventanaInicialLayout = new javax.swing.GroupLayout(ventanaInicial);
        ventanaInicial.setLayout(ventanaInicialLayout);
        ventanaInicialLayout.setHorizontalGroup(
            ventanaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        ventanaInicialLayout.setVerticalGroup(
            ventanaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ventanaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addComponent(ventanaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_AGENDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AGENDARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_AGENDARActionPerformed

    private void BTN_DASHBOARDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DASHBOARDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_DASHBOARDActionPerformed

    private void BTN_ESPECIALIDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ESPECIALIDADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ESPECIALIDADActionPerformed

    private void BTN_CITASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CITASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_CITASActionPerformed

    private void BTN_DOCTORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DOCTORESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_DOCTORESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuSidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuSidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuSidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuSidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuSidebar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_AGENDAR;
    public javax.swing.JButton BTN_CITAS;
    public javax.swing.JButton BTN_DASHBOARD;
    public javax.swing.JButton BTN_DOCTORES;
    public javax.swing.JButton BTN_ESPECIALIDAD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel ventanaInicial;
    // End of variables declaration//GEN-END:variables
}
